# 基本的な実装

In [3]:
# 必要データ読み込み
import numpy as np
array = np.loadtxt("in.csv", delimiter=",", dtype="float", skiprows=1)
x = array[:, 1:3]
y = array[:, 3:4].ravel()
# print(x)
# print(y)

In [25]:
# 訓練データとテストデータの準備
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=3)

In [26]:
# アルゴリズムの選択
from sklearn import tree  # 決定木
clf = tree.DecisionTreeClassifier()

In [27]:
# 学習
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [28]:
# 予測
predict = clf.predict(x_test)
print("予測結果: {}".format(predict))

予測結果: [3. 3. 1.]


In [22]:
# モデル評価
from sklearn.metrics import accuracy_score
print("正解率: {}".format(accuracy_score(y_test, predict)))

正解率: 0.6666666666666666


In [23]:
print(y_test)
print(predict)

[3. 1. 2.]
[3. 1. 1.]


In [1]:
# scikit-learnのデータで

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()
boston

/opt/anaconda3/envs/ml-study/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California hou

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [4]:
import pandas as pd
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df["MEDV"] = boston.target
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [5]:
x = df.RM.to_frame()
y = df.MEDV

In [8]:
from sklearn.model_selection import train_test_split
(x_train, x_test, y_train, y_test) = train_test_split(x, y, test_size=0.3)

In [10]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [11]:
lr.fit(x_train, y_train)

LinearRegression()

In [12]:
y_pred = lr.predict(x_test)
y_pred

array([16.67918164, 23.74785666, 21.85773346, 31.37585385, 37.40303241,
       25.0015098 , 18.29928724,  9.81301982, 21.09589809, 17.1131385 ,
       19.89046238, 18.54037438, 24.41325717, 20.44014106, 25.10758814,
       32.40770682, 20.71980215, 32.54271562, 15.93663324, 36.05294442,
       18.55001787, 21.95416832, 16.9781297 , 16.68882513, 17.94247827,
       32.84166368, 22.166325  , 19.56258386, 39.36066001, 21.31769826,
       22.88958643, 25.17509254, 21.35627221, 20.03511466, 28.0392078 ,
        6.74639137, 18.82967895, 22.75457763, 14.47082341, 23.33318677,
       22.54242095, 28.22243403,  5.46380777, 16.92026878, 23.41033466,
       18.58859181, 24.9340054 , 33.92173408, 16.9781297 , 15.9655637 ,
       15.59911124, 24.95329237, 37.12337133, 23.93108289, 24.16252654,
       37.29695407, 30.23792254, 20.67158472, 17.15171244, 19.18648792,
       27.28701591, 28.80104317, 17.84604341, 26.74698071, 41.41472247,
       19.33114021, 18.31857421, 10.44948988, 22.95709083, 23.70

In [13]:
print(y_pred[0] * 1000)

16679.181639562074


In [14]:
# model 評価
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
mse

59.31357680058236